---
# OpenVPN Download variables
# --------------------------
openvpn_mirror_location:  "{{ streisand_mirror_location }}/openvpn"
openvpn_mirror_href_base: "/mirror/openvpn"

openvpn_base_download_url: "https://build.openvpn.net/downloads/releases/latest"

openvpn_source_filename:      "openvpn-latest-stable.tar.gz"
openvpn_source_sig_filename:  "{{ openvpn_source_filename }}.asc"
openvpn_source_href:          "{{ openvpn_mirror_href_base }}/{{ openvpn_source_filename }}"
openvpn_source_sig_href:      "{{ openvpn_mirror_href_base }}/{{ openvpn_source_sig_filename }}"

openvpn_windows_installer_filename:     "openvpn-latest-stable-amd64.msi"
openvpn_windows_installer_sig_filename: "{{ openvpn_windows_installer_filename }}.asc"
openvpn_windows_installer_href:         "{{ openvpn_mirror_href_base }}/{{ openvpn_windows_installer_filename }}"
openvpn_windows_installer_sig_href:     "{{ openvpn_mirror_href_base }}/{{ openvpn_windows_installer_sig_filename }}"

openvpn_gpg_keyid: "5ACFEAC6"
openvpn_download_files:
  - { "file": "{{ openvpn_source_filename }}", "sig": "{{ openvpn_source_sig_filename }}" }
  - { "file": "{{ openvpn_windows_installer_filename }}", "sig": "{{ openvpn_windows_installer_sig_filename }}" }

# macOS
tunnelblick_version:  "3.8.4a"
tunnelblick_build:    "5601"
tunnelblick_filename: "Tunnelblick_{{ tunnelblick_version }}_build_{{ tunnelblick_build }}.dmg"
tunnelblick_href:     "{{ openvpn_mirror_href_base }}/{{ tunnelblick_filename }}"
tunnelblick_url:      "https://tunnelblick.net/release/{{ tunnelblick_filename }}"
tunnelblick_checksum: "sha256:a693270cd731875de71819f845ba0ba538c66a0bf12b94672edac2b57f23b48c"
